icc/icc/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
# from produits.views import (
#     CreateCheckoutSessionView,
#     ProductLandingPageView
# )

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('contact/', views.contact, name='contact'),
    path('', views.accueil, name='accueil'),
    # path('produits/', views.produits, name='produits'),
    path('produits/', include('produits.urls')),
    path('accueilAdmin/', views.accueilAdmin, name='accueilAdmin'),
    path('reservations/', include('reservations.urls')),
    path('', views.acces),
    path('compte/', include('compte.urls')),
    path('parametres/', include('parametres.urls')),
    path('contact/', include('contact.urls')),
    path('gererClient/', views.gererClients, name='gererClients'),
    path('gererSalon/', views.gererSalon, name='gererSalon'),
    path('', include('payements.urls')),
    path('commande/', include('commande.urls')),
    # path('produits/', ProductLandingPageView.as_view(), name='Landing-page'),
    # path('create-checkout-session/', CreateCheckoutSessionView.as_view(),name='create-checkout-session'),

]

urlpatterns += staticfiles_urlpatterns()

icc/produits/urls.py
# Zumeri Faton et Châtelain Dorian
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'produits'

urlpatterns = [
    path('', views.home, name='home'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('gererProduits/', views.gererProduit, name='gererProduit'),
    path('ajouter_produit/', views.ajouter_produit, name='ajouter_produit'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/update_item/', views.updateItem, name='update_item'),
    path('<str:pk>/', views.modifier_produit, name='modifier_produit'),
    path('supprimer_produit/<str:pk>', views.supprimer_produit, name='supprimer_produit'),

]

icc/produits/models.py
# Zumeri Faton et Châtelain Dorian
from django.db import models
from django.urls import reverse


# Create your models here.


class Produit(models.Model):
    Categorie_prod = (
        ('Colorés', 'Colorés'),
        ('Permanantés', 'Permanantés'),
        ('Endommagés', 'Endommagés'),
        ('Fins Affaiblis', 'Fins Affaiblis'),
        ('Normaux sains', 'Normaux sains'),
        ('White Silver', 'White Silver'),
        ('Cocoa Brown', 'Cocoa Brown'),
        ('Coral Red', 'Coral Red'),
        ('Saffron Copper', 'Saffron Copper'),
        ('Violet Lavender', 'Violet Lavender'),
        ('Cheveux Stressés', 'Cheveux Stressés'),
        ('En profondeur', 'En profondeur')
    )

    Type_choix = (
        ('Shampoo', 'Shampoo'),
        ('Conditioner', 'Conditioner'),
        ('Treatment', 'Treatment'),
        ('Travel Pack', 'Travel Pack'),
        ('Protector', 'Protector'),
        ('Cream', 'Cream'),
        ('Drops', 'Drops'),
        ('Balm', 'Balm'),
        ('Mist', 'Mist'),
        ('Hydra Oil', 'Hydra Oil'),
        ('Oil', 'Oil'),
        ('Mask', 'Mask'),
        ('Serum', 'Serum'),
    )
    nom = models.CharField(max_length=250)
    type = models.CharField(max_length=250, choices=Type_choix)
    categorie = models.CharField(max_length=250, choices=Categorie_prod)
    image = models.ImageField(null=True, blank=True)
    capacite = models.IntegerField()
    prix_achat = models.DecimalField(decimal_places=2, max_digits=5) #centimes
    prix_vente = models.DecimalField(decimal_places=2, max_digits=5) #centimes
    statut = models.CharField(max_length=250)
    quantite = models.IntegerField()

    def get_absolute_url(self):
        return reverse('index', args=[str(self.id)])

    # @property
    # def imageURL(self):
    #     try:
    #         url = self.image.url
    #     except:
    #         url = ''
    #     return url

    def __str__(self):
        return self.nom

icc/produits/forms.py
# Zumeri Faton et Châtelain Dorian
from django import forms
from .models import Produit


class ProduitForm(forms.ModelForm):
    class Meta:
        model = Produit
        fields = ['nom', 'type', 'categorie', 'image', 'capacite', 'prix_achat', 'prix_vente', 'statut', 'quantite']
        choix = (
            ("En vente", "En vente"),
            ("Pas en vente", "Pas en vente"),
        )
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'categorie': forms.Select(attrs={'class': 'form-control'}),
            # 'image': forms.ImageField(attrs={'class': 'form-control'}),
            'capacite': forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}),
            'prix_achat': forms.TextInput(attrs={'class': 'form-control'}),
            'prix_vente': forms.TextInput(attrs={'class': 'form-control'}),
            'statut': forms.Select(choices=choix, attrs={'class': 'form-control'}),
            'quantite': forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}),
        }

icc/produits/views.py
# Zumeri Faton et Châtelain Dorian
import stripe
from django.shortcuts import render, redirect
from .forms import ProduitForm
from .models import Produit
from django.views import View
from commande.models import *
from django.http import JsonResponse
import json


# Create your views here.


def home(request):
    if request.user.is_authenticated:
        client = request.user.client
        commande, created = Commande.objects.get_or_create(client=client, complete=False)
        items = commande.commandeitem_set.all()
        cartItems = commande.get_cart_items
    else:
        items = []
        commande = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = commande['get_cart_items']

    produits = Produit.objects.all()
    print(produits)
    context = {'produits': produits, 'cartItems': cartItems, 'categorie': Produit.Categorie_prod}
    return render(request, 'produits.html', context)


def cart(request):
    if request.user.is_authenticated:
        client = request.user.client
        commande, created = Commande.objects.get_or_create(client=client, complete=False)
        items = commande.commandeitem_set.all()
        cartItems = commande.get_cart_items
    else:
        items = []
        commande = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = commande['get_cart_items']

    context = {'items': items, 'commande': commande, 'cartItems': cartItems}
    # print(items)
    # print(client)
    # print(commande)
    return render(request, 'cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        client = request.user.client
        commande, created = Commande.objects.get_or_create(client=client, complete=False)
        items = commande.commandeitem_set.all()
        cartItems = commande.get_cart_items
    else:
        items = []
        commande = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = commande['get_cart_items']

    context = {'items': items, 'commande': commande, 'cartItems': cartItems}
    # context = {}
    if request.method == 'POST':
        return redirect('../landing.html', id=2)
    return render(request, 'checkout.html', context)


def gererProduit(request):
    produits = Produit.objects.all()
    return render(request, '../templates/gererProduit.html', {'produits': produits})


def ajouter_produit(request):
    if request.method == "POST":
        fm = ProduitForm(request.POST, request.FILES)
        if fm.is_valid():
            fm.save()
            return redirect('/produits/gererProduits')
    else:
        fm = ProduitForm()
    return render(request, '../templates/ajouter_produit.html', {'form': fm})


def modifier_produit(request, pk):
    if request.method == 'POST':
        pi = Produit.objects.get(id=pk)
        fm = ProduitForm(request.POST, request.FILES, instance=pi)
        if fm.is_valid():
            fm.save()
            return redirect('/produits/gererProduits')
    else:
        pi = Produit.objects.get(id=pk)
        fm = ProduitForm(instance=pi)
    return render(request, '../templates/modifier_produit.html', {'form': fm})


def supprimer_produit(request, pk):
    produit = Produit.objects.get(id=pk)
    if request.method == 'POST':
        produit.delete()
        return redirect('/produits/gererProduits')
    context = {'item': produit}
    return render(request, '../templates/supprimer_produit.html', context)


def updateItem(request):
    data = json.loads(request.body)
    produitId = data['produitId']
    action = data['action']

    print('Action:', action)
    print('produitId:', produitId)

    client = request.user.client
    produit = Produit.objects.get(id=produitId)
    commande, created = Commande.objects.get_or_create(client=client, complete=False)

    commandeItem, created = CommandeItem.objects.get_or_create(commande=commande, produit=produit)

    if action == 'add':
        commandeItem.quantite = (commandeItem.quantite + 1)
    elif action == 'remove':
        commandeItem.quantite = (commandeItem.quantite - 1)

    commandeItem.save()

    if commandeItem.quantite <= 0:
        commandeItem.delete()

    return JsonResponse('Item was added', safe=False)

# stripe.api_key = settings.STRIPE_SECRET_KEY
#
#
# class ProductLandingPageView(TemplateView):
#     template_name = "landing.html"
#
#
#
# class CreateCheckoutSessionView(View):
#     def post(self, request, *args, **kwargs):
#         YOUR_DOMAIN = "http://127.0.0.1:8000/"
#         checkout_session = stripe.checkout.Session.create(
#             payment_method_types=['card'],
#             line_items=[
#                 {
#                     'price_data': {
#                         'currency': 'usd',
#                         'unit_amount': 2000,
#                         'product_data': {
#                             'name': 'Stubborn Attachements'
#                         },
#                     },
#                     'quantity': 1,
#                 },
#             ],
#             mode='payment',
#             success_url=YOUR_DOMAIN + '/success/',
#             cancel_url=YOUR_DOMAIN + '/cancel/',
#         )
#         return JsonResponse({
#             'id': checkout_session.id
#         })

icc/produits/templates/cart.html
{# Zumeri Faton#}
{% extends 'base.html' %}
{% block title %}Panier{% endblock %}
{% load static %}
{% block content %}

    <h3>Panier</h3>
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">

                <a class="btn btn-outline-dark" href="{% url 'produits:home' %}">&#x2190; Continuer mes achats</a>

                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Produits: <strong>{{ commande.get_cart_items }}</strong></h5></th>
                        <th><h5>Total:<strong> {{ commande.get_cart_total }}.-</strong></h5></th>
                        {% if request.user.is_authenticated %}
                            <th>
                                <a style="float: right; margin-right: 5px" class="btn btn-success"
                                   href="{% url 'produits:checkout' %}">Commander</a>
                            </th>
                        {% elif not request.user.is_authenticated %}
                            <th>
                                <a style="float: right; margin-right: 5px" class="btn btn-success"
                                   href="{% url 'inscription' %}">Commander</a>
                            </th>
                        {% endif %}
                    </tr>
                </table>

            </div>

            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Produit</strong></div>
                    <div style="flex:1"><strong>Prix</strong></div>
                    <div style="flex:1"><strong>Quantité</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>

                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{% static item.produit.image.url %}"></div>
                        <div style="flex:2"><p>{{ item.produit.nom }}</p></div>
                        <div style="flex:1"><p>{{ item.produit.prix_vente }}.-</p></div>
                        <div style="flex:1">
                            <p class="quantity">{{ item.quantite }}</p>
                            <div class="quantity">
                                <img data-produit="{{ item.produit.id }}" data-action="add"
                                     class="chg-quantity update-cart" src="{% static 'media/plus.png' %}">

                                <img data-produit="{{ item.produit.id }}" data-action="remove"
                                     class="chg-quantity update-cart" src="{% static 'media/moins.png' %}">
                            </div>
                        </div>
                        <div style="flex:1"><p>{{ item.get_total }}.-</p></div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

icc/produits/templates/charge.html
<h1>Payements effectué</h1>

icc/produits/templates/checkout.html
{# Zumeri Faton #}
{% extends 'base.html' %}
{% block title %}Panier{% endblock %}
{% load static %}
{% block content %}

    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Nom..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Informations sur la livraison:</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" placeholder="Adresse..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" placeholder="Ville..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="state" placeholder="Pays..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="Code postal..">
                        </div>
                    </div><br>
                </form>
            </div>


        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'produits:cart' %}">&#x2190; Retour au panier</a>
                <hr>
                <h3>Récapitulatif de la commande</h3>
                <hr>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{% static item.produit.image.url %}"></div>
                        <div style="flex:2"><p>{{ item.produit.nom }}</p></div>
                        <div style="flex:1"><p>{{ item.produit.prix_vente }}.-</p></div>
                        <div style="flex:1"><p>x{{ item.quantite }}</p></div>
                    </div>
                {% endfor %}

                <h5>Produits: {{ commande.get_cart_items }}</h5>
                <h5>Total: {{ commande.get_cart_total }}.-</h5>
            {#                Dorian Châtelain#}
                <form action="{% url 'charge' %}" method="post">
                    {% csrf_token %}
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="{{ key }}"
                            data-description="Payements Gateway"
                            data-amount={% widthratio commande.get_cart_total 1 100 %}
                            data-locale="auto">
                    </script>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

icc/produits/templates/produits.html
{# Zumeri Faton #}
{% extends 'base.html' %}
{% block title %}Produits{% endblock %}
{% load static %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Produits</title>
    </head>
    <body>
    <div class="row">

        {% for categ,_ in categorie %}
            <h3> {{ categ }} </h3>
            <hr>
            {% for p in produits %}
                {% if p.categorie == categ %}
                    <div class="col-lg-4">
                    {% if p.image%}
                        <img class="thumbnail" src="{% static p.image.url %}" alt="img">
                        {% endif %}
                        <div class="box-element product">
                            <h6><strong>{{ p.nom }}</strong></h6>
                            <hr>
                            <button data-produit="{{ p.id }}" data-action="add"
                                    class="btn btn-outline-secondary add-btn update-cart">Ajouter au panier
                            </button>
                            <h4 style="display: inline-block; float: right">{{ p.prix_vente }}</h4>
                        </div>
                        </br></br>
                    </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </div>


    </html>
    <br><br>

{% endblock %}