icc/icc/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
# from produits.views import (
#     CreateCheckoutSessionView,
#     ProductLandingPageView
# )

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('contact/', views.contact, name='contact'),
    path('', views.accueil, name='accueil'),
    # path('produits/', views.produits, name='produits'),
    path('produits/', include('produits.urls')),
    path('accueilAdmin/', views.accueilAdmin, name='accueilAdmin'),
    path('reservations/', include('reservations.urls')),
    path('', views.acces),
    path('compte/', include('compte.urls')),
    path('parametres/', include('parametres.urls')),
    path('contact/', include('contact.urls')),
    path('gererClient/', views.gererClients, name='gererClients'),
    path('gererSalon/', views.gererSalon, name='gererSalon'),
    path('', include('payements.urls')),
    path('commande/', include('commande.urls')),
    # path('produits/', ProductLandingPageView.as_view(), name='Landing-page'),
    # path('create-checkout-session/', CreateCheckoutSessionView.as_view(),name='create-checkout-session'),

]

urlpatterns += staticfiles_urlpatterns()

icc/parametres/urls.py
# Châtelain Dorian
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'parametres'

urlpatterns = [
    path('gererSalon/', views.gererSalon, name='gererSalon'),
    path('<str:pk>/', views.modifier_salon, name='modifier_salon'),

]

icc/produits/urls.py
# Zumeri Faton et Châtelain Dorian
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'produits'

urlpatterns = [
    path('', views.home, name='home'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('gererProduits/', views.gererProduit, name='gererProduit'),
    path('ajouter_produit/', views.ajouter_produit, name='ajouter_produit'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/update_item/', views.updateItem, name='update_item'),
    path('<str:pk>/', views.modifier_produit, name='modifier_produit'),
    path('supprimer_produit/<str:pk>', views.supprimer_produit, name='supprimer_produit'),

]

icc/templates/acces.html
{#Dorian Châtelain#}
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}Accueil{% endblock %}

{% block content %}
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: white !important;


		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #64867d;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #3d3d3f !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #3d3d3f !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100 mt-5">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card mt-sm-auto mt-lg-5">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Nom d'utilisateur" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Mot de passe" class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="login">
				   			</div>
					</form>

				</div>

				{% for message in message %}
				<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Vous n'avez pas de compte ? <a href="{% url 'inscription' %}" class="ml-2">Inscription</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>
<br><br><br><br><br><br><br><br><br><br>

</html>

{% endblock %}

icc/templates/accueilAdmin.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <style>
        .btn-primary {
            height: 200px;
            width: 200px;
        }
    </style>

    <div class="container page p-5">
        <h1>Que souhaitez-vous modifier ?</h1>
        <div class="div m-5">
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <button type="button" class="btn btn-primary btn-lg my-5"
                            onclick="location.href='{% url 'produits:gererProduit' %}'">Produits
                    </button>
                </div>
                <div class="col text-white d-flex justify-content-center">
                    <button type="button" class="btn btn-primary btn-lg my-5" onclick="location.href='{% url 'test' %}'">Réservations</button>
                </div>
            </div>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <a href="../compte/gererClients/">
                    <button type="button" class="btn btn-primary btn-lg my-5">Clients
                    </button></a>
                </div>
                <div class="col d-flex justify-content-center">
                    <button type="button" class="btn btn-primary btn-lg my-5"
                            onclick="location.href='{% url 'prestations-admin' %}'">Prestations
                    </button>
                </div>
            </div>
             <div class="row">
                <div class="col d-flex justify-content-center">
                    <a href="../parametres/gererSalon">
                    <button type="button" class="btn btn-primary btn-lg my-5">Salon
                    </button></a>
                </div>
                <div class="col d-flex justify-content-center">
                    <button type="button" class="btn btn-primary btn-lg my-5"
                            onclick="location.href='{% url 'gererCommande' %}'">Commandes
                    </button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

icc/templates/ajouter_produit.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <div class="row frms">
        <div class="col-sm-4">
            <h4 class="alert alert-info">Ajouter produit</h4>
            <form action="{% url 'produits:ajouter_produit' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" href="{% url 'produits:gererProduit' %}" class="btn btn-success"
                       value="Ajouter produit">
            </form>
        </div>
    </div>
{% endblock %}

icc/templates/base.html
{# Zumeri Faton, Stojkovic Nikola, Châtelain Dorian #}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript">
        var user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!-- Lien CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}Accueil{% endblock %}</title>
</head>
<body style="width: 100%; height: 100%;">
<nav class="navbar navbar-expand-sm w-100 py-2 navbar-dark" style="background-color: #3d3d3f">
    <div class="container-fluid">
        <a href="{% url 'accueil' %}">
            <img src="{% static 'media/logo.jpg' %}" class="img-fluid w-auto" alt="logo"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 d-flex">
                <li class="nav-item">
                    <a class="nav-link" style="color: #7FFFD4; font-size: 25px;" href="{% url 'produits:home' %}">Produits</a>
                </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: #7FFFD4; font-size: 25px;" href="{% url 'mes-reservations' %}">Réservations</a>
                </li>
            {% endif %}
                <li class="nav-item">
                    <a class="nav-link" style="color: #7FFFD4; font-size: 25px;" href="{% url 'test-prestation' %}">Prestations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: #7FFFD4; font-size: 25px;"
                       href="{% url 'contact' %}">Contact</a>
                </li>


                <li class="nav-item dropdown ms-lg-auto">

                    <div class="form-inline my-2 my-lg-0" style="display: inline-block;">
                        <a href="{% url 'produits:cart' %}">
                            <img id="cart-icon" src="{% static 'media/cart.png' %}">
                        </a>
                        <p id="cart-total">{{cartItems}}</p>
                    </div>

                    <a class="nav-link dropdown-toggle" style="color: #7FFFD4; font-size: 25px; display: inline-block"
                       href="#"
                       id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Compte
                    </a>

                    {% if request.user.is_authenticated and not user.is_staff %}

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'profile' %}">Modifier compte</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url "quitter" %}">Déconnexion</a></li>
                        </ul>

                    {% elif request.user.is_authenticated and user.is_staff %}

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'accueilAdmin' %}">Admin</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url "quitter" %}">Déconnexion</a></li>
                        </ul>

                    {% else %}
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'acces' %}">Connexion</a></li>
                            <li><a class="dropdown-item" href="{% url 'inscription' %}">Inscription</a></li>
                        </ul>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</nav>

<br>
<div class="container main">
    {% block content %}

    {% endblock %}
</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
-->

</body>

<footer>
    <div>
        Copyright © 2021 | {{ parametres.nomSalon }} | {{ parametres.adresse }}, {{ parametres.codePostal }} |
        + {{ parametres.telephone }}
    </div>
</footer>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</html>

icc/templates/gererClients.html
{# Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <h1>Souhaitez-vous ajouter des clients ?</h1><br><br><br>

    <div class="col">
        <h5>Clients:</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Username</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Genre</th>
                    <th>Commentaire</th>
                    <th>Mise à Jour</th>
                    <th>Supprimer</th>
                </tr>
                {% for client in clients %}
                    <tr>
                        <th>{{ client.user }}</th>
                        <th>{{ client.nom }}</th>
                        <th>{{ client.prenom }}</th>
                        <th>{{ client.telephone }}</th>
                        <th>{{ client.genre }}</th>
                        <th>{{ client.commentaire }}</th>
                        <th><a class='btn btn-sm btn-dark' href="{% url 'modifier_client' client.id %}">Modifier</a>
                        </th>
                        <th><a class='btn btn-sm btn-danger' href="{% url 'supprimer_client' client.id %}">Supprimer</a>
                        </th>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

icc/templates/gererProduit.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}



    {#    <div class="col-md-7">#}
    <h4>Les produits</h4>
    <BR><BR>
    <div class="card card-body">
        <a class="btn " style="color: #7FFFD4; background-color: #3d3d3f" href="{% url 'produits:ajouter_produit' %}">Ajouter
            un produit</a>
        <hr>
        <table class="table table-sm">
            <tr>
                <th>Produit</th>
                <th>Type</th>
                <th>ml.</th>
                <th>Catégorie</th>
                <th>Prix d'achat</th>
                <th>Prix de vente</th>
                <th>Statut</th>
                <th>Quantité</th>
                <th>Mise à Jour</th>
                <th>Supprimer</th>
            </tr>
            {% for n in produits %}
                <tr>
                    <th><p>{{ n.nom }}</p></th>
                    <th><p>{{ n.type }}</p></th>
                    <th><p>{{ n.capacite }}</p></th>
                    <th><p>{{ n.categorie }}</p></th>
                    <th><p>CHF {{ n.prix_achat }}</p></th>
                    <th><p>CHF {{ n.prix_vente }}</p></th>
                    <th><p>{{ n.statut }}</p></th>
                    <th><p>{{ n.quantite }}</p></th>
                    <th><a class='btn btn-sm btn-dark' href="{% url 'produits:modifier_produit' n.id %}">Modifier</a>
                    </th>
                    <th><a class='btn btn-sm btn-danger'
                           href="{% url 'produits:supprimer_produit' n.id %}">Supprimer</a></th>
                </tr>
            {% endfor %}

        </table>
    </div>
    </div>

{% endblock %}

icc/templates/gererSalon.html
{#Châtelain Dorian#}
{% extends 'base.html' %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>Salon</title>

    <h1>Souhaitez-vous modifier des informations sur le salon ?</h1><br><br><br>


        <ul class="list-group list-group-flush w-25">
            <li class="list-group-item"><h6>Nom :</h6>{{ parametres.nomSalon }}</li>
            <li class="list-group-item"><h6>Téléphone :</h6>+{{ parametres.telephone }}</li>
            <li class="list-group-item"><h6>Adressse :</h6>{{ parametres.adresse }}</li>
            <li class="list-group-item"><h6>Code postal :</h6>{{ parametres.codePostal }}</li>
            <li class="list-group-item"><h6>Email :</h6>{{ parametres.mail }}</li>
            <li class="list-group-item"><h6>Stock minimal pour la vente :</h6>{{ parametres.stockMinPVente }}</li>
            <li class="list-group-item"><h6>Prix de la livraison :</h6>{{ parametres.prixLivraison }}</li>
            <li class="list-group-item"><a class='btn btn-sm btn-dark'
                                           href="{% url 'parametres:modifier_salon' parametres.id %}">Modifier</a></li>
        </ul>

{% endblock %}

icc/templates/landing.html
<div>
    <h1>Here is our product </h1>
    <p>buy now</p>
</div>

icc/templates/modifierCompte.html
{#Dorian Châtelain#}
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}Accueil{% endblock %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
{% endblock %}

icc/templates/modifier_client.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <div class="row frms">
        <div class="col-sm-8 offset-2">
            <h4 class="alert alert-info">Ajouter un commentaire / note.</h4>
            <form action="" method="POST">
                <br>
                {% csrf_token %}
                {{ commentaire }}
                <br>
                <input type="submit" class="btn btn-success" value="Modifier">
            </form>
        </div>
    </div>


{% endblock %}

icc/templates/modifier_salon.html
{#Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-sm-8 offset-2">
            <h4 class="alert alert-info">Modifier les informations du salon</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-success" value="Enregistrer">
            </form>
        </div>
    </div>


{% endblock %}

icc/templates/supprimer_client.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <br><br><h3>Etes-vous sur de vouloir supprimer cette commande ?</h3><br><br>
    <form action="{% url 'supprimer_client' item.id %}" method="post">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'gererClient' %}">Annuler</a>
        <input class="btn btn-danger" href="{% url 'gererClient' %}" type="submit" value="Confirmer">
    </form>
{% endblock %}

icc/templates/supprimer_commande.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <br><br><h3>Etes-vous sur de vouloir supprimer cette commande ?</h3><br><br>
    <form action="{% url 'supprimer_commande' item.id %}" method="post">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'gererCommande' %}">Annuler</a>
        <input class="btn btn-danger" href="{% url 'gererCommande' %}" type="submit" value="Confirmer">
    </form>
{% endblock %}

icc/templates/supprimer_produit.html
{#Zumeri Faton et Dorian Châtelain#}
{% extends 'base.html' %}

{% block content %}

    <br><br><h3>Etes-vous sur de vouloir supprimer cette commande ?</h3><br><br>
    <form action="{% url 'produits:supprimer_produit' item.id %}" method="post">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'produits:gererProduit' %}">Annuler</a>
        <input class="btn btn-danger" href="{% url 'produits:gererProduit' %}" type="submit" value="Confirmer">
    </form>
{% endblock %}